import DashboardLayout from "@/Helper/DashBoardLayout";
import { Inter } from "next/font/google";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scripture-Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}
      style={{
        margin:"0",
        width:"100vw",
        height:"100vh"
      }}
      ><DashboardLayout>{children}</DashboardLayout></body>
    </html>
  );
}
